name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI is running"
